name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion au registre GitHub Packages
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 3 : Build l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/supianbek/ue19-lab-05:latest .

      # Étape 4 : Poussez l'image sur le registre GitHub Packages
      - name: Push Docker image
        run: |
          docker push ghcr.io/supianbek/ue19-lab-05:latest
