# Nom du workflow, ici j'ai mis le nom en fonction de ce qu'on a au labo à la question3
name: DOcker

# Déclencheur du workflow, ici on veut que le workflow soit déclenché à chaque fois qu'on push sur la branche main
on:
  push:
    branches:
      - main

# Les jobs du workflow, ici on a un job qui s'appelle "build"
jobs:
  build:
    # Environnement d'exécution : machine virtuelle Linux
    runs-on: ubuntu-latest

    # Permissions pour accéder à GitHub Packages
    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write

    steps:
      # Étape 1 : Récupère le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure Docker Buildx pour des fonctionnalités avancées de build
      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Se connecter au GitHub Docker Registry
      - name: Se connecter au GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io # Registre de conteneurs de GitHub
          username: ${{ github.actor }} # On utilise le nom de l'utilisateur GitHub qui a déclenché le workflow
          password: ${{ secrets.GITHUB_TOKEN }} # Authentifier avec un jeton d'accès GitHub generé par GitHub Actions automatiquement(cf. https://docs.github.com/fr/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token)

      # Étape 4 : Construire le conteneur et le publier sur le registre GitHub Packages
      - name: Construire le conteneur et le publier sur le registre GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: . # Utilise le répertoire courant pour construire l'image
          push: true
          tags: ghcr.io/Supianbek/ue19-lab-05 # identifiant de l'image Docker taguée avec le mon nom d'user(en minuscule) et le nom du repo

      # Étape 5 : Scanner l'image Docker pour les vulnerabilites (cf. https://trivy.dev/v0.17.2/)
      - name: Scanner l'image Docker pour les vulnerabilites
        uses: aquasecurity/trivy-action@master # On utilise l'action "trivy" pour scanner l'image Docker
        with:
          image-ref: ghcr.io/luffy0xcyber/ue19-lab-05
