name: Docker

on:
  schedule:
    - cron: '45 16 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Installer Trivy avec cache pour la base de données
      - name: Install Trivy and cache database
        run: |
          VERSION="0.26.0"  # Version de Trivy
          
          # Installer jq si non installé (pour traiter l'API GitHub si besoin)
          sudo apt-get install jq -y
          
          # Vérification de la dernière version de Trivy
          TRIVY_URL="https://github.com/aquasecurity/trivy/releases/download/${VERSION}/trivy_${VERSION}_Linux-x86_64.tar.gz"
          
          # Télécharger Trivy
          curl -sfL "$TRIVY_URL" -o trivy.tar.gz
          
          # Extraire Trivy
          tar zxvf trivy.tar.gz
          
          # Déplacer Trivy dans le PATH
          sudo mv trivy /usr/local/bin/
          
          # Répertoire de la base de données Trivy
          TRIVY_DB_DIR="$HOME/.cache/trivy"
          
          # Mise en cache de la base de données Trivy
          - name: Cache Trivy database
            uses: actions/cache@v2
            with:
              path: $TRIVY_DB_DIR
              key: ${{ runner.os }}-trivy-db-${{ hashFiles('**/Dockerfile', '**/app.py') }}  # Vous pouvez ajuster les fichiers déclencheurs ici
              restore-keys: |
                ${{ runner.os }}-trivy-db-

      # Scanner l'image Docker pour les vulnérabilités avec Trivy
      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --no-progress --exit-code 1 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
